In [1]:
import numpy as np

## DateTypes & Attributes 

In [3]:
# NumPy's main datatype ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [12]:
a2 =np.array([[1,2,3], [4,5,6.7]])

a3=np.array([[1,2,4], [6,7,6], [65,123,12321]])

In [13]:
a2

array([[ 1. ,  2. ,  3. ],
       [ 4. ,  5. ,  6.7]])

In [14]:
a3

array([[    1,     2,     4],
       [    6,     7,     6],
       [   65,   123, 12321]])

In [15]:
a1.shape

(3,)

In [16]:
a2.shape

(2, 3)

In [17]:
a3.shape

(3, 3)

In [18]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 2)

In [19]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [20]:
a1.size, a2.size, a3.size

(3, 6, 9)

In [21]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [23]:
#Create a DataFrame from a NumPy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.7

## 2. Create Arrays

In [25]:
sample_array=np.array([1,2,3])
sample_array

array([1, 2, 3])